export const SET_SEARCH_ITEM = "SET_SEARCH_ITEM";
export const SET_QUERY_TYPE = "SET_QUERY_TYPE";
export const SET_QUERY_PARAMS_VALUE = "SET_QUERY_PARAMS_VALUE";
export const SET_QUERY_PARAMS_KEY = "SET_QUERY_PARAMS_KEY";
export const ADD_KEY_VALUE_TO_TOTAL = "ADD_KEY_VALUE_TO_TOTAL";
export const SET_QUERY_PARAMS_ID = "SET_QUERY_PARAMS_ID";
export const REMOVE_PARAM_PAIR = "REMOVE_PARAM_PAIR";
export const SET_JSON_DATA = "SET_JSON_DATA";
